name: linux-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install deps
      run: sudo apt-get install -y build-essential libsdl2-dev libglew-dev gettext
    - name: make
      run: make -C src/ -j4
    - name: upload
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: invader_imgui_sdl2